spring:
  datasource:
    url: jdbc:h2:mem:characters;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driverClassName: org.h2.Driver
    hikari:
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 20000
      maximum-pool-size: 10
      idle-timeout: 600000
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
  transaction:
    rollback-on-commit-failure: true
  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  security:
    user:
      name: starwarsadmin
      password: 5*v3Duez&FHyM#cS
  cloud:
    openfeign:
      client:
        config:
          starWarsClient:
            url: https://swapi.dev/api/
            connectTimeout: 1000
            readTimeout: 30000
            loggerLevel: FULL
            retryer: com.api.challenge.client.rest.FeignRetryer
  api-docs:
    path: /star-wars-api
  show-actuator: true
  swagger-ui:
    enabled: true
    urls-primary-name: 'public'
    filter: true
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoints.web.exposure.include: "*"

#debug: true